api = "0.2"
[buildpack]
id = "custom/custom-buildpack-python"
homepage = "https://github.com/chaitanyakusumba/custom-buildpack-python"
version = "0.0.1"
name = "Python"

  [publish.Ignore]
  files = [
    "test/",
    ".gitignore",
    ".dockerignore",
    ".github/",
    "Dockerfile",
    "Pipfile",
    "Pipfile.lock"
  ]
[[stacks]]
id = "com.digitaldots.stacks.python"