description = "Altoros example CNB builder"

# Included buildpacks

[[buildpacks]]
id = "custom/custom-buildpack-python"
version = "0.0.1"
uri = "docker://custom/buildpack:python"

# Buildpack order detection

[[order]]
[[order.group]]
id = "custom/custom-buildpack-python"
version = "0.0.1"

# Stack definition
[stack]
id = "com.digitaldots.stacks.python"
build-image = "custom/build-image:python"
run-image = "custom/run-image:python"